// Code generated by "callbackgen -type JMChart"; DO NOT EDIT.

package indicator

import ()

func (inc *JMChart) OnUpdate(cb func(value KData)) {
	inc.UpdateCallbacks = append(inc.UpdateCallbacks, cb)
}

func (inc *JMChart) EmitUpdate(value KData) {
	for _, cb := range inc.UpdateCallbacks {
		cb(value)
	}
}
