// Code generated by "callbackgen -type JWMChart"; DO NOT EDIT.

package indicator

import ()

func (inc *JWMChart) OnUpdate(cb func(value KInfo)) {
	inc.UpdateCallbacks = append(inc.UpdateCallbacks, cb)
}

func (inc *JWMChart) EmitUpdate(value KInfo) {
	for _, cb := range inc.UpdateCallbacks {
		cb(value)
	}
}
