# usage:
#
#   go run ./cmd/bbgo optimize --config jeffm.yaml  --optimizer-config jeffm_optimizer.yaml --debug
#
---
executor:
  type: local
  local:
    maxNumberOfProcesses: 10

matrix:
# - type: string
#   label: startTime
#   path: '/backtest/startTime'
#   values: [ "2022-08-01", "2022-11-01" ]

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/limitLowerHightTimes'
#   label: limitLowerHightTimes
#   max: 5
#   min: 0
#   step: 1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/winLeftCount'
#   label: winLeftCount
#   max: 6
#   min: 6
#   step: 1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/winRightCount'
#   label: winRightCount
#   max: 9
#   min: 9
#   step: 1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/vmaWindow'
#   label: vmaWindow
#   max: 5
#   min: 1
#   step: 1
  

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/increaseVolScale'
#   label: increaseVolScale
#   max: 1.3
#   min: 1
#   step: 0.1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/gainVolPreDayScale'
#   label: gainVolPreDayScale
#   max: 1.2
#   min: 0.1
#   step: 0.1


# - type: range
#   path: '/exchangeStrategies/0/jeffmw/increasePriceScale'
#   label: increasePriceScale
#   max: 1
#   min: 0.1
#   step: 0.1


# - type: range
#   path: '/exchangeStrategies/0/jeffmw/amplificationPercent'
#   label: amplificationPercent
#   max: 0.01
#   min: 0
#   step: 0.001

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/changeRatio'
#   label: changeRatio
#   max: 1
#   min: 0
#   step: 0.1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/upperPowerRatio'
#   label: upperPowerRatio
#   max: 1
#   min: 0
#   step: 0.1

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/upperShadowRatio'
#   label: upperShadowRatio
#   max: 0.9
#   min: 0.5
#   step: 0.05

 
# - type: range
#   path: '/exchangeStrategies/0/jeffmw/winMaxMul'
#   label: winMaxMul
#   max: 100
#   min: 5
#   step: 5

# - type: range
#   path: '/exchangeStrategies/0/jeffmw/allowRightUpPercent'
#   label: allowRightUpPercent
#   max: 0.2
#   min: 0
#   step: 0.01


- type: range
  path: '/exchangeStrategies/0/jeffmw/forwardWidth'
  label: forwardWidth
  max: 7
  min: 0
  step: 1

- type: range
  path: '/exchangeStrategies/0/jeffmw/highLoseLeftIndexMin'
  label: highLoseLeftIndexMin
  max: 300
  min: 0
  step: 100
