# usage:
#
#   go run ./cmd/bbgo optimize --config jeffm.yaml  --optimizer-config jeffm_optimizer.yaml --debug
#
---
executor:
  type: local
  local:
    maxNumberOfProcesses: 10

matrix:
# - type: string
#   label: startTime
#   path: '/backtest/startTime'
#   values: [ "2022-08-01", "2022-11-01" ]

- type: range
  path: '/exchangeStrategies/0/jeffm/movingAverage/window'
  label: window
  max: 19
  min: 5
  step: 1

- type: range
  path: '/exchangeStrategies/0/jeffm/checkVolumeMultiple'
  label: checkVolumeMultiple
  max: 5.0
  min: 1.0
  step: 0.5

- type: range
  path: '/exchangeStrategies/0/jeffm/upperPowerStand'
  label: upperPowerStand
  max: 0.9
  min: 0.5
  step: 0.1

- type: range
  path: '/exchangeStrategies/0/jeffm/lowerPowerStand'
  label: lowerPowerStand
  max: 0.9
  min: 0.5
  step: 0.1

- type: range
  path: '/exchangeStrategies/0/jeffm/vmaUpperRatio'
  label: vmaUpperRatio
  max: 1.2
  min: 1
  step: 0.05
  
